FORMAT: 1A
HOST: https://test.amazonaws.com/Dev

# Premier X API

Premier X Api list

## Roles [/role]

### List All Roles [GET]

This api will list all the available roles in the system

+ Response 200 (application/json)

        {
            "status":"OK","statusCode":"200","data":[{"id":1,"title":"Super Admin","status":1,"createdDate":"2017-08-01T11:41:39.000Z"},{"id":2,"title":"License Holder","status":1,"createdDate":"2017-08-01T11:42:04.000Z"},{"id":3,"title":"Admin","status":1,"createdDate":"2017-08-01T11:42:14.000Z"},{"id":4,"title":"Event Organizer","status":1,"createdDate":"2017-08-01T11:42:53.000Z"},{"id":5,"title":"Event Admin","status":1,"createdDate":"2017-08-01T11:43:00.000Z"},{"id":6,"title":"Event Participant","status":1,"createdDate":"2017-08-01T11:43:09.000Z"},{"id":7,"title":"User","status":1,"createdDate":"2017-08-01T11:43:16.000Z"},{"id":8,"title":"Visitor","status":1,"createdDate":"2017-08-01T11:43:21.000Z"}],"message":"Role retrived successfully !"
        }